include: package:lint/strict.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
  exclude:
    - '**.g.dart'
    - '**.mocks.dart'
    # - 'test/'

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at:
# - https://dart-lang.github.io/linter/lints/options/options.html
# - https://dart-lang.github.io/linter/lints/index.html.
# - https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Easier readability
    lines_longer_than_80_chars: true

    # Relative imports are neat!
    always_use_package_imports: false
    prefer_relative_imports: true

    # conditional statements are better
    prefer_if_elements_to_conditional_expressions: false

    # Sorted packages, sorted life :)
    sort_pub_dependencies: true

    # Trying Single quotes
    prefer_single_quotes: true
    # # Double quotes are easily visible
    # prefer_double_quotes: true
