name: tripor
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Run Pubspec Script (RPS) https://pub.dev/packages/rps
scripts:
  fix:
    apply: dart fix --apply
    dry: dart fix --dry-run
  format: dart format --fix .
  generate:
    build: fvm flutter pub run build_runner build --delete-conflicting-outputs
    watch: fvm flutter pub run build_runner watch --delete-conflicting-outputs
  get: fvm flutter pub get

dependencies:
  cached_network_image: ^3.2.3
  chronicle: ^0.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_google_places_hoc081098: ^2.0.0-beta.0
  flutter_hooks: ^0.20.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.0.0
  get_it: ^7.6.0
  go_router: ^10.1.0
  google_api_headers: ^2.0.2
  google_maps_flutter: ^2.4.0
  hooks_riverpod: ^2.3.8
  lint: ^2.1.2
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
